//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonPets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public int ID { get; set; }
        public Nullable<int> owner_id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Species { get; set; }
    
        public virtual Persons Persons { get; set; }
    }
}
