//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServiceLibrary
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyCompositeType", Namespace="http://schemas.datacontract.org/2004/07/MyServiceLibrary")]
    public partial class MyCompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float MyFloatValueField;
        
        private string MyStringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MyFloatValue
        {
            get
            {
                return this.MyFloatValueField;
            }
            set
            {
                this.MyFloatValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MyStringValue
        {
            get
            {
                return this.MyStringValueField;
            }
            set
            {
                this.MyStringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyService")]
public interface IMyService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/Sum", ReplyAction="http://tempuri.org/IMyService/SumResponse")]
    int Sum(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/Sum", ReplyAction="http://tempuri.org/IMyService/SumResponse")]
    System.Threading.Tasks.Task<int> SumAsync(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/Product", ReplyAction="http://tempuri.org/IMyService/ProductResponse")]
    int Product(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/Product", ReplyAction="http://tempuri.org/IMyService/ProductResponse")]
    System.Threading.Tasks.Task<int> ProductAsync(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SumOfAllToN", ReplyAction="http://tempuri.org/IMyService/SumOfAllToNResponse")]
    int SumOfAllToN(int n);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SumOfAllToN", ReplyAction="http://tempuri.org/IMyService/SumOfAllToNResponse")]
    System.Threading.Tasks.Task<int> SumOfAllToNAsync(int n);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetLines", ReplyAction="http://tempuri.org/IMyService/GetLinesResponse")]
    string[] GetLines(string filename);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetLines", ReplyAction="http://tempuri.org/IMyService/GetLinesResponse")]
    System.Threading.Tasks.Task<string[]> GetLinesAsync(string filename);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyService/GetDataUsingDataContractResponse")]
    MyServiceLibrary.MyCompositeType GetDataUsingDataContract(MyServiceLibrary.MyCompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyService/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<MyServiceLibrary.MyCompositeType> GetDataUsingDataContractAsync(MyServiceLibrary.MyCompositeType composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyServiceChannel : IMyService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyServiceClient : System.ServiceModel.ClientBase<IMyService>, IMyService
{
    
    public MyServiceClient()
    {
    }
    
    public MyServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Sum(int a, int b)
    {
        return base.Channel.Sum(a, b);
    }
    
    public System.Threading.Tasks.Task<int> SumAsync(int a, int b)
    {
        return base.Channel.SumAsync(a, b);
    }
    
    public int Product(int a, int b)
    {
        return base.Channel.Product(a, b);
    }
    
    public System.Threading.Tasks.Task<int> ProductAsync(int a, int b)
    {
        return base.Channel.ProductAsync(a, b);
    }
    
    public int SumOfAllToN(int n)
    {
        return base.Channel.SumOfAllToN(n);
    }
    
    public System.Threading.Tasks.Task<int> SumOfAllToNAsync(int n)
    {
        return base.Channel.SumOfAllToNAsync(n);
    }
    
    public string[] GetLines(string filename)
    {
        return base.Channel.GetLines(filename);
    }
    
    public System.Threading.Tasks.Task<string[]> GetLinesAsync(string filename)
    {
        return base.Channel.GetLinesAsync(filename);
    }
    
    public MyServiceLibrary.MyCompositeType GetDataUsingDataContract(MyServiceLibrary.MyCompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public System.Threading.Tasks.Task<MyServiceLibrary.MyCompositeType> GetDataUsingDataContractAsync(MyServiceLibrary.MyCompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
}
