using MyServiceLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EX08_ClientConsoleApp {
    class Program {
        static void Main(string[] args) {            
            MyServiceClient client = new MyServiceClient();

            Console.WriteLine("Sum         : 34 + 65 = " + client.Sum(34, 65));
            Console.WriteLine("Product     : 7  + 9  = " + client.Product(7, 9));
            Console.WriteLine("SumOfAllToN : 101     = " + client.SumOfAllToN(101));

            // Note that client.GetLines returns a string array
            // instead of List<string> in svcutil autogenerated code!
            string[] lines = client.GetLines(@"C:\user\CSharp\EksaminationsGrundlag.txt");
            foreach (var line in lines)
                Console.WriteLine(line);

            MyCompositeType comp_in = new MyCompositeType();
            comp_in.MyFloatValue = 4.5F;
            comp_in.MyStringValue = "<input>";

            Console.WriteLine("Processing MyCompositeType:\n");
            Console.WriteLine("comp_in.MyFloatValue = " + comp_in.MyFloatValue);
            Console.WriteLine("comp_in.MyStringValue = " + comp_in.MyStringValue);

            var comp_out = client.GetDataUsingDataContract(comp_in);
            Console.WriteLine("Serulting MyCompositeType:\n");
            Console.WriteLine("comp_out.MyFloatValue = " + comp_out.MyFloatValue);
            Console.WriteLine("comp_out.MyStringValue = " + comp_out.MyStringValue);
            
            client.Close();

            Console.ReadKey();
        }
    }
}
