//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationZipCodes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zip
    {
        public int Id { get; set; }
        public string ZipName { get; set; }
        public int ZipCode { get; set; }
    }
}
