//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace øvl02.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biografbillet
    {
        public string filmnavn { get; set; }
        public System.DateTime dato { get; set; }
        public System.TimeSpan tid { get; set; }
        public int sæderække { get; set; }
        public int stolenummer { get; set; }
        public string kundeNr { get; set; }
    
        public virtual Kunde Kunde { get; set; }
    }
}
