//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KunderIBioEntities : DbContext
    {
        public KunderIBioEntities()
            : base("name=BiografKunde")
        {
        }
    
      
    
        public virtual DbSet<Biografbillet> Biografbillet { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
    }
}
