//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public int Weight { get; set; }
        public Nullable<int> Score { get; set; }
        public bool Accepted { get; set; }
    }
}
